#!/usr/bin/env bash

# --- CONFIGURATION ---
readonly GH_USER="jediBui"
readonly TARGET_USER="${SUDO_USER:-$USER}"
readonly TARGET_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)

# TARS-style logging
log() {
    local color="$1"; shift
    case "$color" in
        "red")    local code='\033[0;31m' ;;
        "green")  local code='\033[0;32m' ;;
        "yellow") local code='\033[1;33m' ;;
        *)        local code='\033[0m'    ;;
    esac
    echo -e "${code}TARS: $*$nc\033[0m"
}

# Ensure we aren't talking to a vacuum
[[ $EUID -ne 0 ]] && log "red" "Error: Run with sudo. I can't do my job if I'm locked in a box." && exit 1

# 1. Detect Desktop Environment
HAS_GUI=false
if command -v Xorg >/dev/null || command -v weston >/dev/null || [ -d /usr/share/xsessions ]; then
    HAS_GUI=true
    log "yellow" "I've detected a GUI. Preparing the view screens for RDP."
fi

# 2. Dependencies & SSH Installation
log "yellow" "Installing the essentials... and a few luxuries."
apt update && apt install -y \
    curl git openssh-server bash-completion fzf ufw \
    $( [ "$HAS_GUI" = true ] && echo "xrdp" )

# 3. RDP Setup (If Desktop)
if [ "$HAS_GUI" = true ]; then
    log "yellow" "Configuring RDP on port 3389..."
    systemctl enable --now xrdp
    # Add xrdp to the ssl-cert group so it can read the keys
    adduser xrdp ssl-cert
    ufw allow 3389/tcp
fi

# 4. SSH Hardening & Keys
log "yellow" "Securing SSH for $TARGET_USER and fetching GitHub keys..."
install -d -m 700 -o "$TARGET_USER" -g "$TARGET_USER" "$TARGET_HOME/.ssh"
curl -s "https://github.com/${GH_USER}.keys" >> "$TARGET_HOME/.ssh/authorized_keys"
chmod 600 "$TARGET_HOME/.ssh/authorized_keys"
chown "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.ssh/authorized_keys"

cat <<EOF > /etc/ssh/sshd_config.d/99-hardened.conf
PasswordAuthentication no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
EOF

# 5. Firewall Configuration
log "yellow" "Setting up the perimeter defense..."
ufw allow ssh
ufw --force enable

systemctl restart ssh

# 6. Starship
if ! command -v starship &>/dev/null; then
    log "yellow" "Installing Starship. It’s better than a monochrome HUD."
    curl -sS https://starship.rs/install.sh | sh -s -- -y
fi

# 7. DEPLOY CUSTOM .BASHRC
log "yellow" "Deploying customized .bashrc..."
cp "$TARGET_HOME/.bashrc" "$TARGET_HOME/.bashrc.bak"

cat <<'EOF' > "$TARGET_HOME/.bashrc"
# AUTO-GENERATED BY TARS SETUP
[ -z "$PS1" ] && return
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=10000

# Starship & fzf
eval "$(starship init bash)"
[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash
[ -f /usr/share/doc/fzf/examples/completion.bash ] && source /usr/share/doc/fzf/examples/completion.bash

# Completion
[ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

# Smart History Arrows
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

alias ll='ls -alF'
alias ..='cd ..'
EOF

chown "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.bashrc"

log "green" "Configuration complete. System status: Solid. Cooper would be proud."
