#!/usr/bin/env bash

# --- CONFIGURATION ---
readonly GH_USER="jediBui"
readonly TARGET_USER="${SUDO_USER:-$USER}"
readonly TARGET_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)

log() {
    local color="$1"; shift
    local yellow='\033[1;33m' green='\033[0;32m' red='\033[0;31m' nc='\033[0m'
    echo -e "${!color}TARS: $*$nc"
}

[[ $EUID -ne 0 ]] && log "red" "Error: Run with sudo." && exit 1

# 1. Dependencies
log "yellow" "Installing the essentials..."
apt update && apt upgrade && apt clean
apt update && apt install -y curl git openssh-server bash-completion fzf

# 2. Starship
if ! command -v starship &>/dev/null; then
    log "yellow" "Installing Starship..."
    curl -sS https://starship.rs/install.sh | sh -s -- -y
fi

# 3. SSH Hardening
log "yellow" "Securing SSH for $TARGET_USER..."
install -d -m 700 -o "$TARGET_USER" -g "$TARGET_USER" "$TARGET_HOME/.ssh"
curl -s "https://github.com/${GH_USER}.keys" >> "$TARGET_HOME/.ssh/authorized_keys"
chmod 600 "$TARGET_HOME/.ssh/authorized_keys"
chown "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.ssh/authorized_keys"

cat <<EOF > /etc/ssh/sshd_config.d/99-hardened.conf
PasswordAuthentication no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
EOF
systemctl restart ssh

# 4. DEPLOY CUSTOM .BASHRC
log "yellow" "Deploying customized .bashrc..."

# Backup existing .bashrc just in case
cp "$TARGET_HOME/.bashrc" "$TARGET_HOME/.bashrc.bak"

# Overwrite with our clean version
cat <<'EOF' > "$TARGET_HOME/.bashrc"
# AUTO-GENERATED BY TARS SETUP
[ -z "$PS1" ] && return
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=10000

# Starship & fzf
eval "$(starship init bash)"
[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash
[ -f /usr/share/doc/fzf/examples/completion.bash ] && source /usr/share/doc/fzf/examples/completion.bash

# Completion
[ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

# Smart History Arrows
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

alias ll='ls -alF'
alias ..='cd ..'
EOF

chown "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.bashrc"

log "green" "System ready. Plenty of space in the ship."
