#!/usr/bin/env bash

# --- CONFIGURATION ---
readonly GH_USER="jediBui"
readonly TARGET_USER="${SUDO_USER:-$USER}"
readonly TARGET_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)

# TARS-style logging
log() {
    local color="$1"; shift
    local red='\033[0;31m' green='\033[0;32m' yellow='\033[1;33m' nc='\033[0m'
    case "$color" in
        "red")    local code=$red ;;
        "green")  local code=$green ;;
        "yellow") local code=$yellow ;;
        *)        local code=$nc ;;
    esac
    echo -e "${code}TARS: $*$nc"
}

# Ensure we have the clearance
[[ $EUID -ne 0 ]] && log "red" "Error: Run with sudo. I don't have the permissions to override the airlock." && exit 1

# 1. Detect Desktop Environment
HAS_GUI=false
if command -v Xorg >/dev/null || [ -d /usr/share/xsessions ]; then
    HAS_GUI=true
    log "yellow" "GUI detected. Setting up the windows to the outside world (RDP)."
fi

# 2. Dependencies & QEMU Agent
log "yellow" "Provisioning tools... including the Proxmox QEMU Agent."
apt update && apt install -y \
    curl git openssh-server bash-completion fzf ufw qemu-guest-agent \
    $( [ "$HAS_GUI" = true ] && echo "xrdp" )

# 3. Enable Guest Agent
# This allows Proxmox to talk to the VM. Honesty parameter: 95%.
log "yellow" "Starting QEMU Guest Agent... communication lines open."
systemctl enable --now qemu-guest-agent

# 4. RDP Setup (If Desktop)
if [ "$HAS_GUI" = true ]; then
    log "yellow" "Configuring RDP on port 3389..."
    systemctl enable --now xrdp
    adduser xrdp ssl-cert
    ufw allow 3389/tcp
fi

# 5. SSH Hardening & GitHub Keys
log "yellow" "Retrieving keys for ${GH_USER} and locking the hatch..."
install -d -m 700 -o "$TARGET_USER" -g "$TARGET_USER" "$TARGET_HOME/.ssh"
curl -s "https://github.com/${GH_USER}.keys" >> "$TARGET_HOME/.ssh/authorized_keys"
chmod 600 "$TARGET_HOME/.ssh/authorized_keys"
chown "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.ssh/authorized_keys"

cat <<EOF > /etc/ssh/sshd_config.d/99-hardened.conf
PasswordAuthentication no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
EOF

# 6. Firewall Configuration
log "yellow" "Updating firewall. I'm letting SSH in, but everyone else stays out."
ufw allow ssh
ufw --force enable
systemctl restart ssh

# 7. Starship CLI
if ! command -v starship &>/dev/null; then
    log "yellow" "Installing Starship. Standardizing the interface."
    curl -sS https://starship.rs/install.sh | sh -s -- -y
fi

# 8. DEPLOY CUSTOM .BASHRC
log "yellow" "Polishing the control panel (.bashrc)..."
[ -f "$TARGET_HOME/.bashrc" ] && cp "$TARGET_HOME/.bashrc" "$TARGET_HOME/.bashrc.bak"

cat <<'EOF' > "$TARGET_HOME/.bashrc"
# AUTO-GENERATED BY TARS SETUP
[ -z "$PS1" ] && return
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=10000

# Starship & fzf
eval "$(starship init bash)"
[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash
[ -f /usr/share/doc/fzf/examples/completion.bash ] && source /usr/share/doc/fzf/examples/completion.bash

# Completion
[ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

# Smart History Arrows
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

alias ll='ls -alF'
alias ..='cd ..'
EOF

chown "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.bashrc"

log "green" "System fully operational. Don't forget to enable 'QEMU Guest Agent' in the Proxmox VM options."
